### ISSUE TITLE
[Bug]: Error when trying to create a new page

### ISSUE THREAD

**Issue by CareTiger** [nuxtrdev/nuxtr-vscode#1]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.0.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@8.19.1
- Builder:          vite
- User Config:      typescript, css, app, modules, googleFonts, routeRules, runtimeConfig, nitro, devtools, image
- Runtime Modules:  @storyblok/nuxt@5.4.4, @nuxtjs/tailwindcss@6.6.7, @nuxt/image-edge@1.0.0-28050764.aaee7ac, @nuxt/devtools@0.4.5, @nuxtjs/supabase@0.3.5, nuxt-icon@0.4.0, @nuxtjs/google-fonts@3.0.0
- Build Modules:    -
------------------------------

### What went wrong?

i was trying to create a new page and i got this error
![nuxtr error](https://user-images.githubusercontent.com/6777660/236647724-57935172-7bcf-4b04-88b9-57057fdcd5ba.png)

### How to reproduce it?

Steps to reproduce
after following the (instructions)[https://github.com/nuxtrdev/nuxtr-vscode] i tried to create a new vue page 

Expected behavior's
a new vue page with template tags and script setup and style placeholders

Actual behavior
Error attached.

**Comment by adhamfarrag** [comment]
Hi @CareTiger. I just tried testing on Windows 11 VM and didn't face any issue. Can you try again and share console errors you see?
