### ISSUE TITLE
[Bug]: Created page get extra empty lines

### ISSUE THREAD

**Issue by BananaAcid** [nuxtrdev/nuxtr-vscode#100]
### Environment

- Operating System: `Darwin` == MacOS + VSCode
- Node Version:     `v20.5.0`
- Nuxt Version:     `3.8.2`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `npm@10.2.3`
- Builder:          `-`
- User Config:      `devtools`, `build`, `modules`, `vite`
- Runtime Modules:  `()`
- Build Modules:    `-`

### What went wrong?

Extra empty lines, please ignore the Nuxt3 missing type for nuxtApp.

<img width="2034" alt="Bildschirmfoto 2023-12-18 um 14 51 50" src="https://github.com/nuxtrdev/nuxtr-vscode/assets/1894723/d708e634-aa62-4ef2-b92c-adbfcf74370a">

### How to reproduce it?

1. create a template by using the sidebar
2. then CMD+SHIFT+P > Nuxtr: Create new Page

Lucky me: I thought you might be a Windows-Only-Developer, so had an Idea:

Default setting for VSCode on MacOS is CRLF (`\r\n`) on all new files. -- resaving each template file with LF  helps.

**Comment by adhamfarrag** [comment]
@BananaAcid Nuxtr should detects ends of line based on your OS.. will look into it.
