### ISSUE TITLE
Disable devtools popup for nuxt version higher than 3.8

### ISSUE THREAD

**Issue by BayBreezy** [nuxtrdev/nuxtr-vscode#106]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.19.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      devtools, modules, experimental, tailwindcss, colorMode, typescript, imports
- Runtime Modules:  @nuxtjs/tailwindcss@6.10.1, @nuxtjs/color-mode@3.3.2, @vueuse/nuxt@10.7.0, nuxt-icon@0.6.7
- Build Modules:    -
------------------------------

### What went wrong?

Upon opening VSCode, the prompt to install devtools is showing up even tho it is included in Nuxt from v3.8 and up.

### How to reproduce it?

- Create a new Nuxt project
- Remove the devtools dependency from your package.json file
- Reload VSCode

**Comment by adhamfarrag** [comment]
@BayBreezy Thanks for mentioning this issue. Fixed and will release a new version soon.
