### ISSUE TITLE
[Bug]: Nuxtr is requesting to "downgrade" @nuxt/image from 1.3.0 to 0.7.2

### ISSUE THREAD

**Issue by Smart-Ace-Designs** [nuxtrdev/nuxtr-vscode#113]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.11.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      devtools, modules, tailwindcss, app, supabase
- Runtime Modules:  @nuxt/ui@2.12.3, @nuxt/image@1.3.0, @vueuse/nuxt@10.7.2, @nuxtjs/supabase@1.1.5
- Build Modules:    -

### What went wrong?

Not sure what the technical term is for it, but the "Nuxtr Dependency Version Watcher" shows that the @nuxt/image package should be downgraded from 1.3.0 back down to 0.7.2.  This seems incorrect to me and heading in the wrong direction 😄 

![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/132539186/40ddbd7e-cf4e-4a99-9109-d8bf6e54993e)

### How to reproduce it?

Add @nuxt/image to the project.

**Comment by adhamfarrag** [comment]
Hi @Smart-Ace-Designs, just got time to respond :) 

I failed to reproduce this incident using both PNPM and NPM, but still good to mention seeing this list on [Nuxt Image's NPM page](https://www.npmjs.com/package/@nuxt/image?activeTab=versions). Somehow it's treating 0.7.2 as a newer version.

Nuxtr relies on CLIs for respective command, in your case it's `npm outdated` and it didn't return Nuxt image as well. I guess it's a NPM bug that's resolved ? Do you still face this issue ?

![2024-01-24 at 6  52 49@2x](https://github.com/nuxtrdev/nuxtr-vscode/assets/23562275/9e82383a-31fa-4d83-b81b-ebf5bdf2efb6)

**Comment by Smart-Ace-Designs** [comment]
Hi - thanks for the reply.  Yes, the problem is now indeed fixed.  So, yeah, looks like maybe a problem with npm at the time that they now fixed.

**Comment by gsabater** [comment]
I'm having the same issue with two packages. The most notorius example is vuedraggrable, which has version 2.24 for vue2, and 4.1.0 for vue3.

Im being invited to downgrade every day and i don't know how to solve.
I have set tag "next" or even the version "4.1.0" on package.json but their npm registry is the same for both versions, and its a little of a shitshow
