### ISSUE TITLE
[Bug]: Nuxt Devtools installation failed

### ISSUE THREAD

**Issue by posilya** [nuxtrdev/nuxtr-vscode#119]
### Environment

- Operating System: Linux
- Node Version:     v20.10.0
- Nuxt Version:     2.17.2
- CLI Version:      3.10.0

### What went wrong?

After installing the extension, a notification appears that you need to install Nuxt Devtools, and if you click Install, after a few seconds a notification will appear `Nuxt Devtools installation failed`.

### How to reproduce it?

1. Install or enable the Nuxtr extension

**Comment by adhamfarrag** [comment]
Hello @posilya, Nuxtr `0.2.16` should include a fix for this issue. Please update.
