### ISSUE TITLE
[Bug]: tailwindcss module cannot be find when using tailwind.config.ts

### ISSUE THREAD

**Issue by philippedasilva-orizone** [nuxtrdev/nuxtr-vscode#120]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.0`
- Nuxt Version:     `3.10.1`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `pnpm@8.15.1`
- Builder:          `-`
- User Config:      `devtools`, `modules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.11.3`
- Build Modules:    `-`

Don't know if it will change anything but I setup my Nuxt3 project to enable Volar Take Over Mode and I set `typescript: { shim: false }` in the `nuxt.config.ts` file

### What went wrong?

I installed tailwindcss using Nuxtr and checking the 3 options on my fresh Nuxt 3 application. It went fine with a success message and when I ran the server, everything was working as intended and tailwindcss classes are well rendered.
However, when I open the `tailwind.config.ts` file, I get an vscode typescript error that says:
`"Cannot find module 'tailwindcss' or its corresponding type declarations.ts(2307)"`
<img width="1279" alt="Screenshot 2024-02-09 at 18 01 45" src="https://github.com/nuxtrdev/nuxtr-vscode/assets/77384971/bfc7b682-a046-4349-aab1-2eb62e58e444">

Nothing is blocking me and a quick workaround would be to use the javascript version.

I still wonder what could be done to solve it and if not, maybe change the file template to the javascript version.

### How to reproduce it?

- Create a new Nuxt3 project using Nuxtr 
- Install tailwindcss using the "Nuxtr: Configure CSS" command
- Pick Tailwindcss from the list
- Pick the 3 provided options
- Run install
- Open `tailwind.config.ts` in vscode

**Comment by adhamfarrag** [comment]
Hi @philippedasilva-orizone,

Just got time to check the issues.

**Short version**: Just install `pnpm i -D tailwindcss@latest` will make this issue gone for some users. 

**Long version**:  I'm still exploring ways to not gently force users to use TypeScript for everything even if I believe it's way better for your development workflow. But here I had two options, either to make the whole process easier with replace partial configuration steps (installation, file creation) with just chosing (JS/TS files) or add it as an extra step but didn't have time to check choices validation with VSCode API docs yet. Was easier for me for now to replace the JS template until I investigate this best decision.

**Comment by adhamfarrag** [comment]
Hello @philippedasilva-orizone, Nuxtr `0.2.16` should include a step to install `tailwindcss` package by default. Please update.
