### ISSUE TITLE
[Bug]: Bun package manager install failed: "No lockfiles found. Install dependencies first?"

### ISSUE THREAD

**Issue by szig83** [nuxtrdev/nuxtr-vscode#128]
### Environment

- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.1
- Package Manager:  bun@1.0.29
- Builder:          -
- User Config:      devtools, modules, tailwindcss, routeRules, security, runtimeConfig
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.4, nuxt-security@1.2.2
- Build Modules:    -

### What went wrong?

When I try to install a package update, I receive the following error message: No lockfiles found. Install dependencies first? It seems to be not handling the Bun binary lock file bun.lockb Despite having set Bun as the default package manager.

### How to reproduce it?

I simply click on the Nuxt dependencies icon added by Nuxtr to vscode and try to install the updates.

**Comment by adhamfarrag** [comment]
Thanks for reporting @szig83. Will let you know once new version is released with the fix.

**Comment by adhamfarrag** [comment]
Hello @adhamfarrag, Nuxtr `0.2.16` should include a fix for this issue. Please update.

**Comment by szig83** [comment]
> Hello @adhamfarrag, Nuxtr `0.2.16` should include a fix for this issue. Please update.

Thx @adhamfarrag, it works perfectly ;)
