### ISSUE TITLE
[Bug]: Nuxtr seems to be not working for me, regardless of what I do.

### ISSUE THREAD

**Issue by S27149** [nuxtrdev/nuxtr-vscode#13]
### Environment

This is the package.json file of a Nuxt3 project.
{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "dev": "nuxt dev",
    "build": "nuxt build",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@babel/core": "latest",
    "@babel/eslint-parser": "latest",
    "@babel/preset-env": "latest",
    "@element-plus/nuxt": "latest",
    "@nuxt/devtools": "latest",
    "@nuxtjs/eslint-config": "latest",
    "@nuxtjs/eslint-config-typescript": "latest",
    "@nuxtjs/eslint-module": "latest",
    "@nuxtjs/google-fonts": "latest",
    "@nuxtjs/tailwindcss": "latest",
    "eslint-plugin-nuxt": "latest",
    "eslint-plugin-vue": "latest",
    "prettier": "latest",
    "@types/node": "^18",
    "eslint": "^8.42.0",
    "nuxt": "^3.5.3",
    "nuxt-swiper": "latest"
  }
}

### What went wrong?

I have installed VsCode and the latest version of the Nuxt v0.1.3 plugin. However, whenever I try to open a Nuxt3 project, the Nuxt Devtools in the bottom right corner displays "Not Found," and the icon remains red. It prompts me to install Nuxt Devtools, but even after waiting for a long time, nothing happens. I hope to receive your assistance. I'm using a Mac with the M1 Pro chip, and all my system and software versions are up to date. The Nuxt version I'm using is also the latest one.

### How to reproduce it?

It's possible that the issues you're experiencing with the Nuxt3 project are related to your location in mainland China. The problem might be occurring during the installation process when you open the Nuxt3 project after downloading the Nuxtr plugin in VsCode. The Nuxtr icon in the bottom right corner continues to show an installation process.
<img width="1912" alt="截屏2023-06-13 10 43 49" src="https://github.com/nuxtrdev/nuxtr-vscode/assets/72686391/cd68fb88-686d-47c7-8432-6dab951a1818">
![截屏2023-06-12 14 23 36](https://github.com/nuxtrdev/nuxtr-vscode/assets/72686391/ea1186a9-d7b6-4d04-8b53-cbea567a0e21)

**Comment by adhamfarrag** [comment]
Hey Edision, @S27149 

Installing Nuxt Devtools isn't locally, it does install it globally. on Mac you shouldn't have an issue with it. Can you try again and share the console logs from VSCode from Help > Toggle Developer Tool ?

**Comment by S27149** [comment]
Do you want me to globally install the @nuxt/devtools module on my Mac?

**Comment by S27149** [comment]
I'm glad to hear that installing the @nuxt/devtools module globally on your local machine has resolved the issue. It's great to know that the Nuxtr plugin in VSCode is now working and its icon has turned green. You're welcome! If you have any further questions or need additional assistance, feel free to ask. Happy coding!
<img width="1912" alt="截屏2023-06-13 16 47 21" src="https://github.com/nuxtrdev/nuxtr-vscode/assets/72686391/abf611e5-5f8a-4bdc-ba37-6fe7f558cac2">

**Comment by adhamfarrag** [comment]
Glad it's fixed for you and yes, happy coding. 💚
Please, let us know if you have any issue. 
Have a great day @S27149
