### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by RyanChen979** [nuxtrdev/nuxtr-vscode#135]
### Environment

nuxi@3.11.1

### What went wrong?

Every time a new file was made and definePageMeta({}) was declared in the script section, an error would pop up saying "Cannot find name 'definePageMeta'"
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/113121132/99481bf8-7c27-4cef-9b25-f8564e0ef22c)

### How to reproduce it?

Make a new file and create the template using vbase-3-ts-setup. Then add definePageMeta({}) in the script section of the code.

**Comment by RyanChen979** [comment]
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/113121132/5c02869c-8c3d-4afe-955e-7ab8ce211e72)

**Comment by adhamfarrag** [comment]
@RyanChen979 Thanks for sharing this biut I'm looking for the Nuxtr extension version. You can find it by checking extension sidebar view, filter using `@installed nuxtr`. Click on it and you can see the version.

Also, please share your Volar version too.

**Comment by RyanChen979** [comment]
Nuxtr: v0.2.16
Volar: v2.0.10

**Comment by BayBreezy** [comment]
Hey @RyanChen979 , This will happen from time to time even if you create the file manually.
What I do to get around this is just reload the VSCode instance and the warning/error goes away.

A nice little extension exists that makes reloading really easy. it can be found here: https://marketplace.visualstudio.com/items?itemName=natqe.reload

Try it out and let us know 😄

**Comment by adhamfarrag** [comment]
Just noticed your rely @RyanChen979, hi @BayBreezy  :) 

This issue has nothing to do with Nuxtr but TypeScript / Auto Importing support. After migrating to Volar 2 it's getting less and less but still happens. And my way around it is to use `nuxt prepare` command as reloading VSCode doesn't always solve the problem.

Working on hot reloading issues with next major release that should come before Initial Nuxt 4 release date :)

**Comment by adhamfarrag** [comment]
Closing for now, please open if you still need any help.
