### ISSUE TITLE
[Bug]: Error "Nuxtr: No package manager found"  when trying to run a action

### ISSUE THREAD

**Issue by victor-perez** [nuxtrdev/nuxtr-vscode#142]
### Environment

```
- Operating System: Linux
- Node Version:     v20.11.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.15
- Builder:          -
- User Config:      srcDir, build, devtools, vite, ssr, modules
- Runtime Modules:  @vite-pwa/nuxt@0.7.0, ()
- Build Modules:    -
```

nuxtr config
```json
{
  "nuxtr.monorepoMode.DirectoryName": "apps/front-end",
  "nuxtr.defaultPackageManager": "Yarn",
}
```

### What went wrong?

When using mono repo setting the actions don't work, get error "Nuxtr: No package manager found" even if manager is set in the config

![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/672958/9ee29fc1-18ac-4134-9dfa-f402a9af0288)

### How to reproduce it?

nuxtr config
```json
{
  "nuxtr.monorepoMode.DirectoryName": "apps/front-end",
  "nuxtr.defaultPackageManager": "Yarn",
}
```

and click on any action

**Comment by aqz236** [comment]
---

I ran into the same issue with my monorepo, but I’ve already fixed it. Here’s how I did it:

---

📦 **monorepo-main**  
 ┣ 📂 **apps**  
 ┃ ┣ 📂 **nuxt**  
 ┃ ┃ ┣ 📜 **nuxt.config.ts**  // Nuxt config file  
 ┃ ┃ ┣ 📜 **pnpm-lock.yaml**  // This is an empty file, used to trick Nuxt into thinking it's using pnpm  
 ┃ ┃ ┗ 📜 **package.json**    // Nuxt package.json  
 ┃ ┗ 📂 **other**  
 ┗ 📜 **package.json**         // monorepo-main package.json  
 ┗ 📜 **pnpm-lock.yaml**       // monorepo-main pnpm-lock.yaml  

---

Hope that helps! Let me know if you need more details.
