### ISSUE TITLE
[Bug]: If components directory does not exist creating a component does not work

### ISSUE THREAD

**Issue by corbinu** [nuxtrdev/nuxtr-vscode#149]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     ^3.11.2
- CLI Version:      3.12.0
- Nitro Version:    -
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      devtools, modules, googleFonts
- Runtime Modules:  @nuxtjs/tailwindcss@^6.12.0, @nuxtjs/google-fonts@^3.2.0
- Build Modules:    -
------------------------------

### What went wrong?

When creating a component if the components directory doesn't already exist the directory components will be created but the component will not be

### How to reproduce it?

1. Create a new nuxt project via nuxi
2. Try to create a component without creating the components folder

**Comment by adhamfarrag** [comment]
Hello @corbinu, 

Just got the space to pick up the project and respond. 

I tried reproducing the issue with latest version `0.2.16` and couldn't. Which version are you using? Are you still facing this issue?

**Comment by corbinu** [comment]
@adhamfarrag I am no longer seeing the issue in latest VS Code.
