### ISSUE TITLE
[bug]: dependency warning doesn't consider rc

### ISSUE THREAD

**Issue by Sandros94** [nuxtrdev/nuxtr-vscode#15]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@9.2.0
- Builder:          vite
- User Config:      modules, devtools, googleFonts, tailwindcss, colorMode, directus, image, app, $production, $development
- Runtime Modules:  @vueuse/nuxt@10.2.0, @nuxtjs/google-fonts@3.0.1, @nuxthq/ui@2.4.0, @nuxt/image@1.0.0-rc.1, nuxt-directus@5.4.4
- Build Modules:    -
------------------------------

### What went wrong?

Following the notification for Nuxtr dependency warning I get a notification even when dealing with release candidates.
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/13056429/80b9dc10-e8f1-4a82-aac7-ea1511271985)

### How to reproduce it?

Install `@nuxt-image@1.0.0-rc.1` and wait for the bottom right Nuxtr icon to notify that some dependencies are outdated.

**Comment by adhamfarrag** [comment]
Clsoing it as and adding rc consideration to the roadmap.
