### ISSUE TITLE
[Bug]: Running action does not support monorepo

### ISSUE THREAD

**Issue by offizium-berndstorath** [nuxtrdev/nuxtr-vscode#152]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.15.0
- Nuxt Version:     ^3.12.4
- CLI Version:      3.12.0
- Nitro Version:    -
- Package Manager:  pnpm@9.7.0
- Builder:          -
- User Config:      compatibilityDate, devtools, modules, colorMode
- Runtime Modules:  @nuxtjs/i18n@^8.3.3, @nuxtjs/tailwindcss@^6.12.1, @pinia/nuxt@^0.5.3, @nuxtjs/color-mode@^3.4.2
- Build Modules:    -
------------------------------

### What went wrong?

```json
// .vscode/settings.json
"nuxtr.monorepoMode.DirectoryName": "anything"
```
running an action result in an error as the required files are in a subfolder

### How to reproduce it?

use nuxt in a monorepo

**Comment by adhamfarrag** [comment]
Hello @offizium-berndstorath 

I tried reproducing the issue using a monorepo and didn't face any issues on my side. If you're still facing this issue, can you please share what error are you facing? 

Closing the issue for now, please feel free to reopen it if you still face this issue. 

![2024-09-22 at 12  10 42@2x](https://github.com/user-attachments/assets/e7eb6542-df8c-4dbf-b7b7-ed648fc65915)
