### ISSUE TITLE
[Bug]: vueBase snippet doesn't follow script default language setttings

### ISSUE THREAD

**Issue by cooldevdotcodes** [nuxtrdev/nuxtr-vscode#156]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.17.0
- Nuxt Version:     -
- CLI Version:      3.13.1
- Nitro Version:    -
- Package Manager:  pnpm@9.9.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### What went wrong?

I set the default language for script tag to JavaScript as below

`"nuxtr.vueFiles.script.defaultLanguage": "js"`

but vueBase snippet still set language to TypeScript

```
<script lang="ts" setup>

</script>

<template>
  <div>
    
  </div>
</template>
```

### How to reproduce it?

- Set the default language for script tag to JavaScript as below

`"nuxtr.vueFiles.script.defaultLanguage": "js"`

- Use vueBase snippet to generate code

**Comment by zhaolinlau** [comment]
@cooldevdotcodes  May I know if you have installed another Vue 3 snippet extension? Because it works fine for me.

![image](https://github.com/user-attachments/assets/5287eab5-fdcd-49d3-b54f-7d56121b7321)

![image](https://github.com/user-attachments/assets/013e79b4-3224-4ab0-9396-681505bd9277)

**Comment by cooldevdotcodes** [comment]
@zhaolinlau I've just checked it again. It works properly but it requires to restart VS Code or reload the VS Code window to take the effect.

**Comment by zhaolinlau** [comment]
@cooldevdotcodes for me, I don't need to restart lol

**Comment by cooldevdotcodes** [comment]
Sadly it doesn't work for me :-( Actually it doesn't work with all Nuxtr's settings, not just the script default language setting.

**Comment by zhaolinlau** [comment]
@cooldevdotcodes hmm... try using my PR one
[nuxtr-vscode-0.2.16.vsix.zip](https://github.com/user-attachments/files/16995583/nuxtr-vscode-0.2.16.vsix.zip)

**Comment by cooldevdotcodes** [comment]
@zhaolinlau I've just installed the extension from your ZIP file and it works perfectly.

- When I change the default language settings, it asks me to reload the window. Seems this behavior is new.
- When I change the first tag settings, it applied immediately.

BTW, vueBase snippet is missing in this one. I can only see vueBaseLayout snippet.

**Comment by zhaolinlau** [comment]
@cooldevdotcodes I think you were using the older version of nuxtr? Because I didn't change the snippet things, I only added a new functionality which is `default language for nuxt files`

**Comment by cooldevdotcodes** [comment]
Nope, I installed Nuxtr VSIX from your ZIP file. In your screenshot (https://github.com/nuxtrdev/nuxtr-vscode/issues/156#issuecomment-2346924328) I also can only see vueBaseLayout.

**Comment by zhaolinlau** [comment]
I mean even I install the original one from vscode market, it also appears the vueBaseLayout only

**Comment by zhaolinlau** [comment]
Could you try uninstalling my version and reinstall the original one from vscode extension market?

**Comment by zhaolinlau** [comment]
@cooldevdotcodes the vueBase snippet got removed in 0.2.16 version of nuxtr

**Comment by cooldevdotcodes** [comment]
@zhaolinlau I tried to install v0.2.16 from VSCode extension market and Nuxtr default language settings doesn't work. Check my video shot https://drive.google.com/file/d/1fCvRCLP__A2SHJLvEBsjfKmwSyfyUtZ6/view?usp=sharing

**Comment by zhaolinlau** [comment]
@cooldevdotcodes Yes, because the feature is not existed in v0.2.16, #159 this is my pull request

**Comment by zhaolinlau** [comment]
If the author/maintainer of this repo merge my pull request #159 , then the feature will only be added in next release

**Comment by zhaolinlau** [comment]
> @zhaolinlau I tried to install v0.2.16 from VSCode extension market and Nuxtr default language settings doesn't work. Check my video shot https://drive.google.com/file/d/1fCvRCLP__A2SHJLvEBsjfKmwSyfyUtZ6/view?usp=sharing

That's a vue file, u should change this setting
![image](https://github.com/user-attachments/assets/fce9e785-7f78-4602-8af4-4372ae775d32)

**Comment by zhaolinlau** [comment]
> @zhaolinlau I tried to install v0.2.16 from VSCode extension market and Nuxtr default language settings doesn't work. Check my video shot https://drive.google.com/file/d/1fCvRCLP__A2SHJLvEBsjfKmwSyfyUtZ6/view?usp=sharing

That's a vue file, u should change this setting
![image](https://github.com/user-attachments/assets/5988a936-f4e1-4bfa-9c40-ce89eee40d5e)

**Comment by adhamfarrag** [comment]
Hello @cooldevdotcodes, @zhaolinlau 

I feel bad to keep issues open but been having issues to respond sooner @cooldevdotcodes :) 

Your original issue is clear, and will make sure next release have the issue fixed. 

`vueBase` wasn't removed from Nuxtr or the PR @zhaolinlau made. There are changes regarding extension API and snippets and I believe more snippets aren't working as expected.

![2024-09-14 at 4  39 06@2x](https://github.com/user-attachments/assets/16be6699-45f7-4733-a466-ec77d77da7b5)

@cooldevdotcodes As much happy I am to see the PR with a major change, it's always better to check the code and build the extension locally yourself after checking these changes instead of installing the VSIX. Please, use `build` and `package` scripts commands for this.

**Comment by zhaolinlau** [comment]
@adhamfarrag Because my PR is based on your latest commit, and the `vueBase` snippet is got removed

**Comment by cooldevdotcodes** [comment]
@zhaolinlau Is there any reason why you remove `vueBase` snippet? I see it more popular than vueBaseLayout.

**Comment by zhaolinlau** [comment]
The code block is gone @adhamfarrag 

![image](https://github.com/user-attachments/assets/fe4bf877-f2dc-4f9a-8a3e-9cf3f51a94ec)

[src/snippets/index.ts](https://github.com/nuxtrdev/nuxtr-vscode/blob/main/src/snippets/index.ts)

**Comment by zhaolinlau** [comment]
> @zhaolinlau Is there any reason why you remove `vueBase` snippet? I see it more popular than `vueBaseLayout`.

I didn't remove it lol, it's got remove by you

**Comment by cooldevdotcodes** [comment]
LOL, I'm not @adhamfarrag :-D

**Comment by zhaolinlau** [comment]
> LOL, I'm not @adhamfarrag :-D

My bad XD, got removed by @adhamfarrag

**Comment by cooldevdotcodes** [comment]
@adhamfarrag Is there any reason why you remove `vueBase` snippet? I see it more popular than `vueBaseLayout`.

**Comment by adhamfarrag** [comment]
Hello @cooldevdotcodes, I didn't mean to delete it. :)
Reopening the issue as I'll work on both issues.

**Comment by adhamfarrag** [comment]
Thanks for reporting this issue @cooldevdotcodes❤️
Pushed a fix and will be added to next release. :)
