### ISSUE TITLE
[bug]: tab spacing breaks when switching on or off devtools icon (b-right)

### ISSUE THREAD

**Issue by Sandros94** [nuxtrdev/nuxtr-vscode#16]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@9.2.0
- Builder:          vite
- User Config:      modules, devtools, googleFonts, tailwindcss, colorMode, directus, image, app, $production, $development
- Runtime Modules:  @vueuse/nuxt@10.2.0, @nuxtjs/google-fonts@3.0.1, @nuxthq/ui@2.4.0, @nuxt/image@1.0.0-rc.1, nuxt-directus@5.4.4
- Build Modules:    -
------------------------------

### What went wrong?

Should be an easy fix, just check for the preferred user settings within vscode settings and see if they are using 2 or 4 spaces for tabs.
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/13056429/472e6e0a-af54-4d67-9f19-6e57788a2bee)

### How to reproduce it?

Configure VSCode tab setting to be at 4 spaces, and try to disable nuxt-devtools with the bottom right icon.

**Comment by adhamfarrag** [comment]
Hey @Sandros94,

I tried to reproduce your issue and wasn't able to reproduce it. I believe it's your linting configuration. If you still face this issue, can you please share your linting configuration for VSCode and Project? 

![2023-07-15 at 01 14 11](https://github.com/nuxtrdev/nuxtr-vscode/assets/23562275/e816a83a-2717-463a-9f6d-1dcf4608e2ee)

**Comment by adhamfarrag** [comment]
Clsoing it for now. Please repon if you still face the issue.

**Comment by Sandros94** [comment]
> If you still face this issue, can you please share your linting configuration for VSCode and Project?

That's the issue... I have no linting configured in my projects (due to the fact that I still need to learn how to properly configure and use it). But before reply I wanted to make sure that none of my installed extension could cause any problems, but even disabling everything but `Nuxtr' I still get this problem.

What is curious tho, is that only the first tab becomes 2 spaces, all the nested ones remain as 4 spaces.

I have no idea where to look this for

**Comment by adhamfarrag** [comment]
I'm `adhamfarrag` on Discord, too. Let's debug this issue more and I'm happy to share the little I know about linting :) ? 
Or maybe within two days I can share my VSCode settings if it can be helpful to you.

**Comment by Sandros94** [comment]
Just for fun and giggles I messed around with the Space/Tab settings in the bottom right corner of VSCode, and I've managed to break even more... (I've activated and deactivated devtools only once🙃)
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/13056429/cbe1f8a9-e4e6-4357-a942-8bd89bbd611a)

> I'm `adhamfarrag` on Discord, too.

Adding you there
