### ISSUE TITLE
[bug]: nuxtr isn't able to pick up devtools if defined inside the `$development` env.

### ISSUE THREAD

**Issue by Sandros94** [nuxtrdev/nuxtr-vscode#17]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@9.2.0
- Builder:          vite
- User Config:      modules, devtools, googleFonts, tailwindcss, colorMode, directus, image, app, $production, $development
- Runtime Modules:  @vueuse/nuxt@10.2.0, @nuxtjs/google-fonts@3.0.1, @nuxthq/ui@2.4.0, @nuxt/image@1.0.0-rc.1, nuxt-directus@5.4.4
- Build Modules:    -
------------------------------

### What went wrong?

When devtools is configured inside the `$development` environment config Nuxtr isn't able to find it ([since v.3.5.0](https://github.com/nuxt/nuxt/releases/tag/v3.5.0)).

nuxt.config.ts:
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/13056429/3648ed8c-ab5b-4132-a20c-66314fbf1ac4)

### How to reproduce it?

nuxt.config.ts:
```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
    modules: [
        /* [...] */
        '@nuxt/devtools',
        /* [...] */
    ],
    /* [...] */
    $development: {
        devtools: {
            enabled: true,
            vscode: {
                enabled: true,
                reuseExistingServer: true,
            },
        },
    },
});
```

**Comment by adhamfarrag** [comment]
Closing the issue for now and adding it to next release scope.
