### ISSUE TITLE
[bug]: nuxtr make `nuxt.config.ts` scroll when typing

### ISSUE THREAD

**Issue by Sandros94** [nuxtrdev/nuxtr-vscode#18]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@9.2.0
- Builder:          vite
- User Config:      modules, devtools, googleFonts, tailwindcss, colorMode, directus, image, app, $production, $development
- Runtime Modules:  @vueuse/nuxt@10.2.0, @nuxtjs/google-fonts@3.0.1, @nuxthq/ui@2.4.0, @nuxt/image@1.0.0-rc.1, nuxt-directus@5.4.4
- Build Modules:    -
------------------------------

### What went wrong?

Video shows simply what is happening:

https://github.com/nuxtrdev/nuxtr-vscode/assets/13056429/466c9853-4e50-47ca-95c4-d42305bc0ece

### How to reproduce it?

Not fully sure, if this could happen on all machines, but I've noticed that either disabling Nuxtr or the `@builtin TypeScript Language Basics` stops the scrolling. Could be related to annotations and buttons conflicting with each other between the code lines.

**Comment by adhamfarrag** [comment]
Thanks for reporting all these bugs @Sandros94, very helpful to us. 

Will look into them as soon as I can.

And for this error, it's on all machines and it's because of Nuxtr actions inside nuxt.config.ts file.

**Comment by adhamfarrag** [comment]
@Sandros94  Fixed in Version 0.1.7. Please update.
