### ISSUE TITLE
[Bug]: "server" folder is not always "server" since I can edit it on nuxt.config.ts

### ISSUE THREAD

**Issue by hugojerez** [nuxtrdev/nuxtr-vscode#19]
### Environment

[12:04:53 AM] Nuxi 3.5.3
[12:04:53 AM] 
[12:04:53 AM] RootDir: /Users/hugo/Documents/fullstack_template
[12:04:53 AM] Nuxt project info: (copied to clipboard)

------------------------------
- Operating System: Darwin
- Node Version:     v16.19.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.10
- Builder:          vite
- User Config:      ssr, srcDir, serverDir, css, components, hooks, runtimeConfig, build, app
- Runtime Modules:  -
- Build Modules:    -
------------------------------

[12:04:53 AM] 👉 Report an issue: https://github.com/nuxt/nuxt/issues/new

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### What went wrong?

Its an error assume that "server" is the default API folder, if someone change it from nuxt config it doent work
<img width="376" alt="image" src="https://github.com/nuxtrdev/nuxtr-vscode/assets/5186975/8a393fa6-6056-4173-9336-3007181b9353">

<img width="163" alt="image" src="https://github.com/nuxtrdev/nuxtr-vscode/assets/5186975/2f046117-5f65-4373-8695-c1c0eb7b9c4b">

---
<img width="170" alt="image" src="https://github.com/nuxtrdev/nuxtr-vscode/assets/5186975/8680679d-d20e-4a4e-ad26-88969166d03e">

---

<img width="131" alt="image" src="https://github.com/nuxtrdev/nuxtr-vscode/assets/5186975/a35fdbb7-49ab-422b-a9aa-861276e5cec5">

---
It asume that I'm working with "server" as Server Folder, but in my nuxt.config.ts I redefine it 

 
<img width="227" alt="image" src="https://github.com/nuxtrdev/nuxtr-vscode/assets/5186975/6fe72def-4d67-4930-b728-5031669e861d">

---

This is the expected behaviour since I redefine server folder in my nuxt.config.ts

<img width="173" alt="image" src="https://github.com/nuxtrdev/nuxtr-vscode/assets/5186975/0cd823f4-a167-44fe-8059-e1cd4427df5c">

### How to reproduce it?

1. create a nuxt3 project in nuxt.config.ts

```
   srcDir: "front/",
   serverDir: "back/",
```

move every front folder and file ( app.vue,error.vue,  public, assets, layouts,server, components, pages, composables,plugins) to front 

move every back folder and file (/api, /middleware, /utils) to back

2. from nuxtr vscode extension select option Create new API and it doesnt work

**Comment by adhamfarrag** [comment]
Closing the issue for now and adding the scope to next release.
