### ISSUE TITLE
[Bug]: Failed to locate Nuxt Devtools, install it?

### ISSUE THREAD

**Issue by angelhdzmultimedia** [nuxtrdev/nuxtr-vscode#20]
### Environment

OS: Windows 11  Home 10.0.22621 Build 22621
Node: 18.15.0
VSCode: 1.80.0 
Nuxtr: 0.1.4 (and 0.1.3)
nuxt: 3.6.2
@nuxt/devtools: 0.3.1
pnpm: 8.6.5

### What went wrong?

![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/10191085/ba1ebdf5-2834-4a71-9e66-aea7eed92e68)

![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/10191085/6a5d6074-8d7b-4f8d-9a11-0163cb35f9a9)

### Attempts to solve it

- Install previous version of Nuxtr extension 
- Install @nuxt/devtools globally
- Install @nuxt/devtools per project
- Install @nuxt/devtools both globally and per project
- Delete .nuxt and restart the app
- Reload VSCode workspace
- Disable and Enable devtools from the Command Pallette

No matter what I try, even though devtools is enabled and working in the browser, the icon is always red and I get the notification in every workspace reload.

### How to reproduce it?

- Open a nuxt app project in VSCode workspace

**Comment by adhamfarrag** [comment]
Hello @angelhdzmultimedia,

Can you share the console errors when you startup your project?

**Comment by angelhdzmultimedia** [comment]
> Hello @angelhdzmultimedia,
> 
> Can you share the console errors when you startup your project? VSCode Console can be opened from Help > Toggle Developer Tools.

![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/10191085/db335264-5e73-422a-9185-c54dfa88e669)

**Comment by adhamfarrag** [comment]
This means all terminal commands don't work on Windows.. Will fix this issue as soon as I can.

**Comment by lihbr** [comment]
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/25330882/51401c90-931e-458f-88e1-68e952d7cfb8)
Logs on my end

**Comment by RihanArfan** [comment]
Also getting this problem using pnpm (with hoisting) on GitHub Codespaces (Linux)

<img alt="image" src="https://github.com/nuxtrdev/nuxtr-vscode/assets/20425781/7ddebb5b-157d-414e-b7d4-d11ef5bb0bc4">

**Comment by adhamfarrag** [comment]
@lihbr Thanks Lucie. :) 

@RihanArfan They should not affect each other. And on Linux, you should get the error if installation fails because of sudo permissions. Installing Nuxt Devtools globally manually should fix it for you.

**Comment by angelhdzmultimedia** [comment]
> 

Yes I confirm. Scaffolding works great.

**Comment by angelhdzmultimedia** [comment]
> Also getting this problem using pnpm (with hoisting) on GitHub Codespaces (Linux)
> 
> Details
> ![image](https://user-images.githubusercontent.com/20425781/252159521-7ddebb5b-157d-414e-b7d4-d11ef5bb0bc4.png)
> EDIT: The scaffold/create commands seem to work despite the error though

Yes I confirm. Scaffolding works great.

**Comment by adhamfarrag** [comment]
@angelhdzmultimedia @RihanArfan Fixed in Version 0.1.7. Please update.
Thanks @lihbr for helping me with this one. :)
