### ISSUE TITLE
[Bug]: Creating a new plugin shouldn't register inside nuxt.config.ts

### ISSUE THREAD

**Issue by RihanArfan** [nuxtrdev/nuxtr-vscode#21]
### Environment

- Operating System: Linux
- Node Version:     v19.9.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.6
- Builder:          vite
- User Config:      modules, runtimeConfig, experimental, typescript, devtools
- Runtime Modules:  @nuxthq/ui@2.5.0, @vueuse/nuxt@10.2.1
- Build Modules:    -

### What went wrong?

When creating a new plugin, it's automatically registered inside `nuxt.config.ts`, which is against what documentation suggest.

See warning on Nuxt docs here https://nuxt.com/docs/guide/directory-structure/plugins#plugins-directory
<img alt="Nuxt warning auto register plugins dir" src="https://github.com/nuxtrdev/nuxtr-vscode/assets/20425781/0153cd7e-d7e8-424a-ae93-c6beb1392217">

### How to reproduce it?

1. Right click plugins directory/open command pallete and choose `Create new plugin`
<img width="198" alt="image" src="https://github.com/nuxtrdev/nuxtr-vscode/assets/20425781/c964a357-410b-4e12-b1ac-81f43da323e6">

2. Enter a name, like `test`
3. See `plugins/test.ts`  but also `nuxt.config.ts` `plugins: ["~/plugins/test.ts"],`

<img alt="nuxt.config.ts plugins registered" src="https://github.com/nuxtrdev/nuxtr-vscode/assets/20425781/c31a05c1-982a-4ec0-b009-cf0d7fe33373">

**Comment by adhamfarrag** [comment]
Thanks @RihanArfan  :) 
This was intentional as we're experimenting with learning curve as users coming from Nuxt 2 to 3. In near future users will get insights inside their editor about such practices.
