### ISSUE TITLE
[Bug]: The tailwind template is incorrect

### ISSUE THREAD

**Issue by Atos-lang** [nuxtrdev/nuxtr-vscode#28]
### Environment

Nuxt3、Tailwind

### What went wrong?

https://github.com/nuxtrdev/nuxtr-vscode/blob/main/src/templates/css.ts
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/79756603/07fbd5d0-be9b-4d55-b453-f50d6f219ae3)
This configuration does not take effect

### How to reproduce it?

You need to add a semicolon here, otherwise the tailwind css  will not take effect
`
@tailwind base;
@tailwind components;
@tailwind utilities;
`

**Comment by adhamfarrag** [comment]
@Atos-lang please provide the environment information using the command.

Also, is doing this happen with creating pages/components with Nuxtr command?

**Comment by Atos-lang** [comment]
this is my env：
`  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/tailwindcss": "^6.8.0",
    "@types/node": "^18.17.3",
    "nuxt": "^3.6.5"
  }`
and create css frameworks with nuxtr command，after selecting tailwind and creating it, the default tailwind.css file does not have a semicolon, causing the tailwind style to not take effect when I use it in pages/components

**Comment by Atos-lang** [comment]
ok
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/79756603/a3d9c813-6ce3-4152-8d9a-d4f4acf9deae)

not effect
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/79756603/d9950a58-d911-4d25-999b-918e896e7b15)

**Comment by adhamfarrag** [comment]
Fixed. Thanks @Atos-lang
