### ISSUE TITLE
[Bug]: Invalid command analyse

### ISSUE THREAD

**Issue by BayBreezy** [nuxtrdev/nuxtr-vscode#3]
### Environment

Nuxt project info

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.20.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@8.19.4
- Builder:          vite
- User Config:      css, build, ssr, modules, sourcemap, app, imports, devtools
- Runtime Modules:  nuxt-typed-router@3.2.0, @davestewart/nuxt-scrollbar@1.0.0, ()
- Build Modules:    -
------------------------------

### What went wrong?

The analyse word should be analyze.

Running the analyse command gives this error:

```bash
$ npx nuxi analyse
Nuxi 3.4.3                                                                                                                           6:13:01 AM
                                                                                                                                     6:13:01 AM
Invalid command analyse
[6:13:01 AM] Usage: npx nuxi dev|build|build-module|cleanup|clean|preview|start|analyze|generate|prepare|typecheck|usage|info|init|create|devtools|upgrade|test|add|new [args]

Use npx nuxi [command] --help to see help for each command
```

### How to reproduce it?

1. Install the extension
2. Bring up command palette
3. Search for "Nuxtr: Run nuxt analyse"

**Comment by adhamfarrag** [comment]
Hello @BayBreezy, thanks for reporting this bug. We already fixed it and it will be available with the next release!
Please, let us know if there's anything else that is unstable with you.

**Comment by adhamfarrag** [comment]
Hello, @BayBreezy 
This issue is now fixed. Please, update Nuxtr!
