### ISSUE TITLE
[Bug]: script type and TS

### ISSUE THREAD

**Issue by ibrahimBeladi** [nuxtrdev/nuxtr-vscode#4]
### Environment

Nuxtr v0.0.6

### What went wrong?

When configuring the script type (nuxtr.vueFiles.script.type), I am getting an interesting behavior.
When it is setup, then it generates: 
```
<script setup lang="ts">

</script>


<template>

</template>
```

When it is normal, it generates: 
```
<script>

</script>


<template>

</template>
```

They should not effect whether TS is being used here or not, also TS or rather the script language should be a separate configuration prop

**Comment by adhamfarrag** [comment]
Ahlan @ibrahimBeladi!
Yes! `lang="ts"` shouldn't exist. We removed it and should be fixed for the upcoming release along with detecting Nuxt 2/3.

I'll revisit this issue once it's fixed.

**Comment by adhamfarrag** [comment]
Ahlan @ibrahimBeladi 

This issue is now fixed with version 0.1.1. Please, update Nuxtr :)
Closing this issue for now. Feel free to reopen it if you face the same issue.

**Comment by xiyaowong** [comment]
@adhamfarrag  I think it would be better to add a configuration option called `nuxtr.vueFiles.script.defaultLanguage`.

**Comment by adhamfarrag** [comment]
@xiyaowong added and should be released today.
