### ISSUE TITLE
[Bug]: No Sidebar / Command

### ISSUE THREAD

**Issue by irvandikky** [nuxtrdev/nuxtr-vscode#47]
### Environment

Nuxi 3.6.5
------------------------------
- Operating System: Windows_NT
- Node Version:     v18.8.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      ssr, nitro, vite, server, app, devtools, modules, pwa, router, routeRules, security, nuxtSanctumAuth, tailwindcss, image
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, nuxt-sanctum-auth@0.4.7, @kevinmarrec/nuxt-pwa@0.17.0, @nuxt/image@1.0.0-rc.1, nuxt-security@0.14.4, @pinia/nuxt@0.4.11
- Build Modules:    -
------------------------------

VSCode
------------------------------
- Version: 1.82.2 (user setup)
- Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
- Date: 2023-09-14T05:55:25.390Z
- Electron: 25.8.1
- ElectronBuildId: 23779380
- Chromium: 114.0.5735.289
- Node.js: 18.15.0
- V8: 11.4.183.29-electron.0
- OS: Windows_NT x64 10.0.22621
------------------------------

### What went wrong?

Hello
I'm already install Nuxtr on my Vscode but there is no sidebar / command in pallete commands
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/51032415/89dcddfd-a84a-457d-8d19-f12924a5d99c)
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/51032415/3f3f0f23-583f-457e-8d6a-f65e692ceda3)

### How to reproduce it?

Install Nuxtr on Vs Code Extension Marketplace

**Comment by adhamfarrag** [comment]
Hey @irvandikky,  just tried on a Windows 11 VM and seems working to me.

1. Is Nuxt project in the root dir ? if not, are you using `"nuxtr.monorepoMode.DirectoryName": "directory-name"` [setting](https://github.com/nuxtrdev/nuxtr-vscode#srcdir-serverdir-and-monorepo-support): 

2. Can you share console logs from VSCode ?

**Comment by irvandikky** [comment]
1. Yes in the root dir.
2. No logs from vscode from the start i open vscode

![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/51032415/94654ea3-0e97-4b10-a925-139110efecaa)

**Comment by adhamfarrag** [comment]
This is output channel. Console logs can be found from **Help** > **Toggle Developer Tools**

<img width="397" alt="2023-09-17 at 22 54 11@2x" src="https://github.com/nuxtrdev/nuxtr-vscode/assets/23562275/9da7e1fa-8005-4a13-87c1-505b8a787d0f">

**Comment by irvandikky** [comment]
Sorry here is the log
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/51032415/d0bf9697-15a8-41d5-885c-3d7c0bfbe975)

**Comment by adhamfarrag** [comment]
From the logs showing up. This is a remote server, right ?

**Comment by irvandikky** [comment]
I'm not using remote server. This project & vscode on my local machine

**Comment by adhamfarrag** [comment]
Ok, my bad. Can you close VSCode, and try testing the extension with a fresh Nuxt app and make sure dependencies are installed ?

**Comment by irvandikky** [comment]
Working fine with the fresh nuxt App.
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/51032415/6059dc2a-d769-4613-8294-0cd87c888d2e)

I think it's workspace / terminal primary folder (project) problem. I use git bash
Nuxt App must be primary folder (project)

**Comment by adhamfarrag** [comment]
Thanks for doing this test. 
It rarely happens but I should debug this case more. But quick solution should be removing `yarn.lock`, dependencies and reinstalling packages.

**Comment by irvandikky** [comment]
Removing yarn.lock with reinstall and reopen vscode working fine

**Comment by adhamfarrag** [comment]
Glad to know! Please, share with us any idea or feedback if this is your first time using Nuxtr. :)
