### ISSUE TITLE
[Bug]: Nuxtr dependencies version checker stuck in loop

### ISSUE THREAD

**Issue by frasza** [nuxtrdev/nuxtr-vscode#57]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.8.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      app, ssr, typescript, vue, css, imports, components, modules, googleFonts, tailwindcss, runtimeConfig, devtools, telemetry
- Runtime Modules:  @nuxtjs/google-fonts@3.0.2, @nuxtjs/tailwindcss@6.8.0, @vueuse/nuxt@10.5.0, @pinia/nuxt@0.4.11
- Build Modules:    -

### What went wrong?

I have been using Nuxtr extension for some time now and were using dependencies version checker daily where I saw what dependencies had newer version available. Yesterday I switched to `fnm` (Fast node manager) and suddenly dependencies version checker doesn't work anymore. It is stuck in infinite loop in the VSC status bar:

![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/22049682/9c97b59c-7765-42a7-90ef-c18134ac9132)

FNM Environment:
```
Node version 20.8.0
```
```
$env:FNM_MULTISHELL_PATH = "C:\Users\user\AppData\Local\fnm_multishells\24104_1697119229842"     
$env:FNM_ARCH = "x64"
$env:FNM_DIR = "C:\Users\user\AppData\Roaming\fnm"
$env:FNM_VERSION_FILE_STRATEGY = "local"
$env:FNM_LOGLEVEL = "info"
$env:FNM_COREPACK_ENABLED = "false"
$env:FNM_NODE_DIST_MIRROR = "https://nodejs.org/dist"
$env:FNM_RESOLVE_ENGINES = "false"
```

### How to reproduce it?

Install FNM on Windows, use latest Node v20.8.0 and open Nuxt project in VSC with Nuxtr extension

**Comment by adhamfarrag** [comment]
Hello @frasza, 

Nuxtr detects and relies on terminal to detect outdated dependencies using `npm(for npm or yarn)/pnpm outdated --json`. I installed FNM and tried to execute the command from terminal and didn't have any issue. 

Can you please try executing the command from terminal and share the results ?

**Comment by frasza** [comment]
Hello @adhamfarrag 

Interesting, running `npm outdated --json` works fine and I get list of dependencies that can be updated. 
```
npm outdated --json
{
  "@antfu/eslint-config": {
    "current": "0.42.1",
    "wanted": "0.42.1",
    "latest": "1.0.0-beta.26",
    "dependent": "web",
    "location": "...\\node_modules\\@antfu\\eslint-config"
  },
  "@tiptap/extension-image": {
    "current": "2.1.11",
    "wanted": "2.1.12",
    "latest": "2.1.12",
    "dependent": "web",
    "location": "..\\node_modules\\@tiptap\\extension-image"
  },
  "@tiptap/extension-placeholder": {
    "current": "2.1.11",
    "wanted": "2.1.12",
    "latest": "2.1.12",
    "dependent": "web",
    "location": "..\\node_modules\\@tiptap\\extension-placeholder"
  },
  "@tiptap/extension-table": {
    "current": "2.1.11",
    "wanted": "2.1.12",
    "latest": "2.1.12",
    "dependent": "web",
    "location": "..\\node_modules\\@tiptap\\extension-table"
  },
  "@tiptap/extension-table-cell": {
    "current": "2.1.11",
    "wanted": "2.1.12",
    "latest": "2.1.12",
    "dependent": "web",
    "location": "..\\node_modules\\@tiptap\\extension-table-cell"
  },
  "@tiptap/extension-table-header": {
    "current": "2.1.11",
    "wanted": "2.1.12",
    "latest": "2.1.12",
    "dependent": "web",
    "location": "..\\node_modules\\@tiptap\\extension-table-header"
  },
  "@tiptap/extension-table-row": {
    "current": "2.1.11",
    "wanted": "2.1.12",
    "latest": "2.1.12",
    "dependent": "web",
    "location": "..\\node_modules\\@tiptap\\extension-table-row"
  },
  "@tiptap/extension-text-align": {
    "current": "2.1.11",
    "wanted": "2.1.12",
    "latest": "2.1.12",
    "dependent": "web",
    "location": "..\\node_modules\\@tiptap\\extension-text-align"
  },
  "@tiptap/starter-kit": {
    "current": "2.1.11",
    "wanted": "2.1.12",
    "latest": "2.1.12",
    "dependent": "web",
    "location": "..\\node_modules\\@tiptap\\starter-kit"
  },
  "@tiptap/vue-3": {
    "current": "2.1.11",
    "wanted": "2.1.12",
    "latest": "2.1.12",
    "dependent": "web",
    "location": "..\\web\\node_modules\\@tiptap\\vue-3"
  }
}
```

But still, for some reason, I still only see loading spinner in VSC status bar.

**Comment by adhamfarrag** [comment]
@frasza Interesting.. can you check VSCode Console on reload ? From Help > Toggle Developer Tools.

**Comment by frasza** [comment]
@adhamfarrag Attaching screenshot ...
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/22049682/be46439b-8c19-44aa-9e86-ec8f40672d64)

Btw, if I init new nuxt project, it seems to be working ... interesting indeed ...
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/22049682/f5a07016-1b9c-4033-8d47-1ead86c1521a)

**Comment by adhamfarrag** [comment]
Even more interesting.. I believe the issue is your lock file. A fresh install should fix it.

**Comment by frasza** [comment]
I have tried removing `node_modules` and `lock` file manually and using `nuxi upgrade --force`, no luck :/

**Comment by adhamfarrag** [comment]
@frasza care to have a debugging call?

**Comment by frasza** [comment]
Hey @adhamfarrag, sure! Let me know how to get in contact.

**Comment by adhamfarrag** [comment]
@frasza Discord ? My username is `adhamfarrag`.

**Comment by adhamfarrag** [comment]
Context for users: 

- We had a debugging session, ended with knowing that the issue is generic with an exception for this project. And it seems to be related to package.json. (Awaiting for @frasza to confirm this).
- What exactly happens is on first loading of VSCode, Nuxtr manages to fetch outdated dependencies, on window reload it gets stuck without any errors. 
- It seems to be a FNM issue more than Nuxtr.

**Comment by adhamfarrag** [comment]
I'll close issue for now.

**Comment by Fizzify** [comment]
Hello, I am having this issue. @adhamfarrag 

You mentioned that it runs the command on the terminal right? Well I have a special case for my terminal shell which makes fnm work, so how would I change the terminal that Nuxtr uses? (I am using Cmder BTW.)

**Comment by Hornwitser** [comment]
I had ~~the same~~ __a different__ issue running Nuxtr on Windows using pnpm as the package manager. In my case it was caused by my `nuxt.config.ts` containing the following:
```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
	compatibilityDate: '2024-11-01',
	devtools: { enabled:  !process.env.DISABLE_DEV_TOOLS },
        // ...
```

Which __caused and endlessly spinning orb on the statusbar and__ logged the following errors in the Developer Tools window:
```
mainThreadExtensionService.ts:78 [Nuxtr.nuxtr-vscode]Casting "UnaryExpression" is not supported

  3 | export default defineNuxtConfig({
  4 | 	compatibilityDate: '2024-11-01',
  5 | 	devtools: { enabled: !process.env.DISABLE_DEV_TOOLS },
                               ^
  6 | 	runtimeConfig: {

mainThreadExtensionService.ts:79 MagicastError: Casting "UnaryExpression" is not supported

  3 | export default defineNuxtConfig({
  4 | 	compatibilityDate: '2024-11-01',
  5 | 	devtools: { enabled: !process.env.DISABLE_DEV_TOOLS },
                               ^
  6 | 	runtimeConfig: {

```

In this case rewriting the `nuxt.config.ts` to the following resolved it:
```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
const enableDevtools = !process.env.DISABLE_DEV_TOOLS
export default defineNuxtConfig({
	compatibilityDate: '2024-11-01',
	devtools: { enabled: enableDevtools },
        // ...
```

## Edit
I realise now that my issue was about the nuxtr devtools toggle on the status bar, not the dependency checker. Sorry about that.
