### ISSUE TITLE
[Bug]: Command not found

### ISSUE THREAD

**Issue by ThomasWT** [nuxtrdev/nuxtr-vscode#6]
### Environment

any

### What went wrong?

Nuxt can't find any commands when connected with [Remote Explorer](https://marketplace.visualstudio.com/items?itemName=ms-vscode.remote-explorer)

![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/1246641/1a3cb2f3-0a62-4bd5-8484-a9a6576836ea)

### How to reproduce it?

1. open VSCode
2. install [Remote Explorer](https://marketplace.visualstudio.com/items?itemName=ms-vscode.remote-explorer)
3. connect to a server with Remote explorer
4. use any command

**Comment by adhamfarrag** [comment]
Hi @ThomasWT 

Can you please share console errors from VSCode?
Also, Does it work properly without the Remote Server?

**Comment by ThomasWT** [comment]
> Hi @ThomasWT
> 
> Can you please share console errors from VSCode? from Help > Toggle Developer Tools. Also, Does it work properly without the Remote Server?

Works fine locally without the remote server.

Here's the console
```
mainThreadExtensionService.ts:112 Activating extension 'Nuxtr.nuxtr-vscode' failed: ENOENT: no such file or directory, open 'undefined'.
$onExtensionActivationError @ mainThreadExtensionService.ts:112
```

**Comment by adhamfarrag** [comment]
@ThomasWT Thanks for sharing this. Will look into it and get back to you once it's fixed.

**Comment by ThomasWT** [comment]
Thanks! Can't wait to introduce it to the junior devs at work 🙏

**Comment by adhamfarrag** [comment]
@ThomasWT Glad to hear you like Nuxtr and wanting to share it with others! 💚

I'd really like to hear comments and thoughts of your junior devs! If you like, feel free to DM me on Twitter (On my Github Profile) or Discord `adhamfarrag#0268`. Team feedback seems to offer more insights for us.

Next release has good features for teams workflow! I'll make sure I mention them here with fixing this issue.

**Comment by ThomasWT** [comment]
Will let you know! 🙏😁

**Comment by mrleblanc101** [comment]
Just installed on my local machine, having the same error.
You can see the plugin installed in the plugin panel on the left.
<img width="1824" alt="Capture d’écran, le 2023-06-15 à 22 53 53" src="https://github.com/nuxtrdev/nuxtr-vscode/assets/17392251/4950c78b-7d9d-42f6-8935-22a1ac4e9f2d">

**Comment by mrleblanc101** [comment]
> Activating extension 'Nuxtr.nuxtr-vscode' failed: ENOENT: no such file or directory, open 'undefined'.

**Comment by adhamfarrag** [comment]
@ThomasWT @mrleblanc101  Fixed in version 0.1.7. Please update.

**Comment by RichardMarchant** [comment]
> On my Mac
> 
> > Activating extension 'Nuxtr.nuxtr-vscode' failed: ENOENT: no such file or directory, open 'undefined'.

Same issue on my Mac with v0.1.10

**Comment by adhamfarrag** [comment]
@RichardMarchant Are you trying to use Nuxtr with a remote server? 
Also, can you share VSCode console logs/errors?
