### ISSUE TITLE
[Bug]: Page generation and VSCode UI

### ISSUE THREAD

**Issue by Blaquewithaq** [nuxtrdev/nuxtr-vscode#62]
### Environment

Nuxt project info:
------------------------------
- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  bun@1.0.6
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### What went wrong?

1. Creating pages, layouts, etc.
- There are currently 3 extra blank lines added to every generated file in between the <script> and <style> tags. I'm OCD about my code so idk if this was intentional or not. lol.

2. The nuxt devtools status icon and the message it presents are opposite of each other.
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/43357960/7c3f61c5-787e-4186-b225-1e701f84f5f2)
See here, i just disabled it and the message says it was enabled.

### How to reproduce it?

1. Create a generated page.

2. Toggle the nuxt devtools button.

**Comment by adhamfarrag** [comment]
@Blaquewithaq I understand the first issue, can you elaborate more about the second one ?

**Comment by Blaquewithaq** [comment]
Okay so when I click to enable: Nuxt Devtools, the pop-up message shown is that it is disabled when it is actually enabled.
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/43357960/be2c7079-cc40-40a4-a0ad-47ab074aad1f)

See how the icon in the bar is green and says enabled, while the popup message behind it shows that it was disabled. This needs to be switched to say "Nuxt Devtools enabled."

**Comment by adhamfarrag** [comment]
@Blaquewithaq, Nuxtr 0.2.4 should contains bug fixes for these issues. Please update and thanks for reporting them!
