### ISSUE TITLE
[Bug]: Issue with bun support

### ISSUE THREAD

**Issue by Blaquewithaq** [nuxtrdev/nuxtr-vscode#63]
### Environment

Nuxt project info:
------------------------------
- Operating System: Linux via WSL
- Node Version:     v18.16.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  bun@1.0.6
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### What went wrong?

When using bun as the default package manager, the commands still use npm as the default manager.

I'm running linux in WSL on windows. I dont have npm install, only bun.

I've checked the developer logs on vscode to find this:

![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/43357960/249cc11d-665e-447a-aa08-c6ea084b5e79)

### How to reproduce it?

Create an environment with ONLY bun (NO NPM). And try to update dependencies or install modules via the Nuxtr extension.

**Comment by Blaquewithaq** [comment]
Update on the issue: 

I downloaded the extension repo and went digging around.

1. bun doesn't have a version of this command: npm view ${package} version
2. bun when run does replacements of everything related to npm,yarn,pnpm,etc,
therefor since there isn't a bun replacement command for this functionality, it is not replaced and therefor wont work.

I'm waiting to hear back from the bun discord on how to handle this.

**Comment by adhamfarrag** [comment]
I love your excitement and thanks for making the time to do the PR! But I wish you [discussed it first](https://github.com/nuxtrdev/nuxtr-vscode#contributing) before making the time to implement it.. 

We're refactoring this feature soon and I'll consider your solution.

**Comment by Blaquewithaq** [comment]
> I love your excitement and thanks for making the time to do the PR! But I wish you [discussed it first](https://github.com/nuxtrdev/nuxtr-vscode#contributing) before making the time to implement it..
> 
> We're refactoring this feature soon and I'll consider your solution.

No problem! If anything was fun to figure out. Cant wait to see what you've got in store

**Comment by adhamfarrag** [comment]
@Blaquewithaq Do you face any issues with Linux via WSL?

**Comment by Blaquewithaq** [comment]
> @Blaquewithaq Do you face any other issues with Linux via WSL?

Yes, there is another problem I came across after doing this PR. The function getOutdatedPackages needs to be reworked because bun does NOT have the command: ```bun outdated```. This causes the update dependencies icon (in the status bar) to always be loading.
