### ISSUE TITLE
[Bug]: Tasks don't run in fish shell

### ISSUE THREAD

**Issue by KnifeFed** [nuxtrdev/nuxtr-vscode#69]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.18.0`
- Nuxt Version:     `3.8.0`
- CLI Version:      `3.9.1`
- Nitro Version:    `2.7.0`
- Package Manager:  `pnpm@8.7.6`
- Builder:          `-`
- User Config:      `build`, `devtools`, `fontMetrics`, `googleFonts`, `i18n`, `ignore`, `image`, `imports`, `modules`, `postcss`, `radash`, `snackbar`, `svgo`, `tailwindcss`, `typescript`, `vite`
- Runtime Modules:  `@nuxt/devtools@1.0.0`, `@nuxt/image@1.0.0-rc.3`, `@nuxtjs/fontaine@0.4.1`, `@nuxtjs/google-fonts@3.0.2`, `@nuxtjs/i18n@8.0.0-rc.4`, `@nuxtjs/tailwindcss@6.8.0`, `@pinia-plugin-persistedstate/nuxt@1.1.2`, `@pinia/nuxt@0.5.1`, `@vueuse/nuxt@10.4.1`, `floating-vue/nuxt`, `nuxt-headlessui@1.1.4`, `nuxt-icon@0.5.0`, `nuxt-radash@1.0.0`, `nuxt-snackbar@1.0.3`, `nuxt-svgo@3.5.4`, `nuxt-typed-router@3.3.1`
- Build Modules:    `-`

### What went wrong?

If I click e.g. `dev` in Nuxtr, under "Actions", the terminal opens and says `pnpm dev` then just shows my prompt. Nothing runs.

### How to reproduce it?

Use fish shell in VSCode. Run an action.

**Comment by adhamfarrag** [comment]
Hi @KnifeFed

I tried to debug it but couldn't reproduce it on a linux VM. 

![2023-10-22 at 12  27 31@2x](https://github.com/nuxtrdev/nuxtr-vscode/assets/23562275/6cedd095-75af-45f4-a8df-2e93e4d28b25)

Can you please share console logs from Help > Toggle Developer tools ?

**Comment by adhamfarrag** [comment]
Please open it again if you still face the issue.
