### ISSUE TITLE
[Bug]: Casting "BinaryExpression" is not supported

### ISSUE THREAD

**Issue by Blaquewithaq** [nuxtrdev/nuxtr-vscode#72]
### Environment

Nuxt project info:
------------------------------
- Operating System: Linux
- Node Version:     v18.18.2
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  bun@1.0.6
- Builder:          -
- User Config:      app, debug, devServer, experimental, modules, runtimeConfig, typescript, vite, devtools, prepareKit, supabase
- Runtime Modules:  @nuxtjs/supabase@1.1.3, nuxt-prepare@0.2.1
- Build Modules:    -
------------------------------

### What went wrong?

Nuxtr seems to throw errors in relation to the usage of {process.env.NODE_ENV === "development"} inside my nuxt.config.ts
```
export default defineNuxtConfig({
  debug: process.env.NODE_ENV === "development",
});
  ```
  
  
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/43357960/803a35b6-3bca-458b-bcc5-2b94ee2b5dac)

### How to reproduce it?

Modify the nuxt.config.ts so that a setting utilizes a conditional operator. Like shown above.

**Comment by adhamfarrag** [comment]
Hi @Blaquewithaq, thanks for being proactive about these issues. Been the most valuable feedback so far for the project. 

![2023-10-22 at 12  23 56@2x](https://github.com/nuxtrdev/nuxtr-vscode/assets/23562275/bf2daf44-b1c2-4da3-bb7b-996bc4caf2c9)

Regarding this bug, I failed to reproduce it. Does it happen when you re/start VSCode? Or upon a certaini action ?

**Comment by Blaquewithaq** [comment]
My apologies, I dug further into it and I posted the wrong example. It only does it on this one:

```
devtools: { enabled: process.env.NODE_ENV === "development" },
```

**Comment by Blaquewithaq** [comment]
Also I'm receiving these errors frequently, idk what they are tho. Haven't dug into it.
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/43357960/f0c3fd4d-7986-4e0b-91a7-1214ec9a34df)

**Comment by adhamfarrag** [comment]
No worries. This is an edge case where Nuxtr Devtools toggle reads the static value of the boolean directly. By default Nuxt Devtools is disabled in production. Please help me understand why do you need to specify it this way ?

**Comment by adhamfarrag** [comment]
Regarding the snippets. Did you disable Nuxtr snippets ?

**Comment by Blaquewithaq** [comment]
> No worries. This is an edge case where Nuxtr Devtools toggle reads the static value of the boolean directly. By default Nuxt Devtools is disabled in production. Please help me understand why do you need to specify it this way ?

I dont and will remove as I didnt realize this lol..

**Comment by Blaquewithaq** [comment]
> Regarding the snippets. Did you disable Nuxtr snippets ?

Eh i dont think so. Im unsure how id even do that.

**Comment by Blaquewithaq** [comment]
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/43357960/7e2469c4-e293-4407-943d-23dad88baddd)

**Comment by adhamfarrag** [comment]
No worries :) 

One of the cools features Nuxt Devtools is allowing Nuxt Devtools in production for demo purposes. Nuxtr looks for either `devtools: {...}` or `$development: { devtools: {...} } ` as the focus is development phase.

```
$development: {
    devtools: {
      enabled: false
    }
  },

  $production: {
    devtools: {
      enabled: true
    }
  }

```

**Comment by adhamfarrag** [comment]
> > Regarding the snippets. Did you disable Nuxtr snippets ?
> 
> Eh i dont think so. Im unsure how id even do that.

Interesting.. can you reinstall Nuxtr? It should solve it for you.

**Comment by Blaquewithaq** [comment]
> > > Regarding the snippets. Did you disable Nuxtr snippets ?
> > 
> > 
> > Eh i dont think so. Im unsure how id even do that.
> 
> Interesting.. can you reinstall Nuxtr? It should solve it for you.
> 
> But before that can you check Nuxtr settings: `"nuxtr.snippets.nuxt": true,` ?

These are my Nuxtr settings, Ive set in my settings.json:
```
// Nuxtr
  "vueFiles.template.defaultLanguage": "html",
  "nuxtr.vueFiles.firstTag": "template",
  "nuxtr.vueFiles.script.type": "setup",
  "nuxtr.vueFiles.script.defaultLanguage": "ts",
  "nuxtr.vueFiles.style.addStyleTag": false,
  "nuxtr.vueFiles.style.alwaysScoped": true,
  "nuxtr.vueFiles.style.defaultLanguage": "scss",
  "nuxtr.openItemsAfterCreation": true,
  "nuxtr.defaultPackageManager": "Bun",
  "nuxtr.intellisense.nuxtrc": true,
  "nuxtr.intellisense.vueFiles": true,
  "nuxtr.intellisense.nuxtignore": true,
  "nuxtr.snippets.nuxt": true,
  "nuxtr.snippets.nitro": true,
  "nuxtr.vueFiles.pages.defaultTemplate": "default.page-template",
  "nuxtr.vueFiles.layouts.defaultTemplate": "default.layout-template"
```

**Comment by adhamfarrag** [comment]
@Blaquewithaq Then can you please reinstall it ?

**Comment by Blaquewithaq** [comment]
A complete uninstall/reinstall of the extension worked. Thank you!
