### ISSUE TITLE
[Bug]: How to use snippets

### ISSUE THREAD

**Issue by Barbapapazes** [nuxtrdev/nuxtr-vscode#74]
### Environment

/

### What went wrong?

Hello,

When I type `template` in a Vue file, I can't access to snippets. Am I doing something wrong?

### How to reproduce it?

/

**Comment by Barbapapazes** [comment]
Hooo, I have to start with `<` in order to view usable snippets.

**Comment by adhamfarrag** [comment]
Hey @Barbapapazes 

Snippets in VSCode works with a prefix. We wanted it to be a natural experience for both Nuxt and Nitro snippets. All what you have to do is type normally the component you want to use and it will show up.

![2023-10-22 at 12  15 32@2x](https://github.com/nuxtrdev/nuxtr-vscode/assets/23562275/f7f09c3b-f877-4c5c-ad00-5dc4d9e3257e)


![2023-10-22 at 12  17 13@2x](https://github.com/nuxtrdev/nuxtr-vscode/assets/23562275/ec1dd226-8358-48f3-951d-097479f96f23)


Nuxtr documentation is under development. Soon we'll offer the full list of snippets and their prefix. But for now I can conform that all Nuxt Components, Utilities and Compsables are supported.

And for Nitro, just type `nitro` and it will list available snippets.

**Comment by Barbapapazes** [comment]
I don't know why but nothing appear.

![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/45267552/8b2e48c7-b5a4-4e27-8a51-acf287118c10)

**Comment by adhamfarrag** [comment]
This is how it should be. 

![2023-10-22 at 1  06 55@2x](https://github.com/nuxtrdev/nuxtr-vscode/assets/23562275/6e6d6bdd-0624-4b5f-998b-f30f5bad4f86)


Can you help me with making sure you have these settings: 

```
 "nuxtr.snippets.nuxt": true,
 "nuxtr.snippets.nitro": true
```

If they exist, then you must have disabled snippets or need to allow them in general using:

```
"editor.tabCompletion": "on",
"editor.snippetSuggestions": "top",
```

**Comment by adhamfarrag** [comment]
@Barbapapazes did you have the time to solve it ? I just started to realize more users can't use snippets on Windows and some Linux distributions out of the box.

**Comment by mathiasayivor** [comment]
Hey @adhamfarrag, I think @Barbapapazes was referring to achieving a similar workflow as the `ES7+ React/Redux/React-Native snippets` plugin. For example, in React, this plugin allows you to generate boilerplate code for an empty functional component by typing `rfce` and pressing `Tab`. It's especially handy after creating a component without using the `Nuxtr` command and needing to quickly fill in the `<script>` and `<template>` blocks.

If I've misunderstood @Barbapapazes, I still think situations like this should be considered. I'd like to be able to generate boilerplate code based on my `Nuxtr` config, especially if I've already created a file, like a component, without using the Create new Component command.

**Comment by adhamfarrag** [comment]
Hey @mathiasayivor, 

1. As Nuxtr already offers configuration and means to create all files, we didn't need to offer full templates with a snippet command. Will explore ways to link dynamic template to a snippet. 
2. Still, we offer all tags separately in case you don't need your typical / customized template. And the behavior is typical to what you expressed, select snippet and press tab. 
3. For @Barbapapazes's case, snippets don't show up at all to check whether the experience is similar to other snippets or not. All I can see showing up for him is TypeScript completions.. and I'm trying to understand why if the suggested solution doesn't work for him.

**Comment by adhamfarrag** [comment]
Hi @Barbapapazes, since you seem to align with what @mathiasayivor said, With 0.2.10, I added two dynamic snippets linked to your Nuxtr configuration for base files / layouts. Please, update.
