### ISSUE TITLE
[Bug]: Nested Composables

### ISSUE THREAD

**Issue by ghzb** [nuxtrdev/nuxtr-vscode#8]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v19.8.1
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.1
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### What went wrong?

When I tried to create a nested composable like `auth/client` it created the folder directory, but did not create the correct function name, or link up the composable so it is automatically imported by Nuxt.

got something like this
```
export const useAuth/login = () => {
  return ref()
}
```

### How to reproduce it?

ran following command in vscode command pallet
```
Nuxtr: Create new composable [auth/client]
```

**Comment by 0kaa** [comment]
Thanks @ghzb for catching this issue, It'll be fixed in the next release

**Comment by adhamfarrag** [comment]
Hello @ghzb, this is now supported with version 0.1.1. Please, update Nuxtr! 
Closing this issue for now. Please, reopen if you face any issues.
