### ISSUE TITLE
[Bug]: srcDir templates location incorrect

### ISSUE THREAD

**Issue by jaketig** [nuxtrdev/nuxtr-vscode#84]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      build, css, imports, lodash, modules, runtimeConfig, srcDir, ssr, vite
- Runtime Modules:  nuxt-lodash@2.5.3, @pinia/nuxt@0.5.1, nuxt-vitest@0.11.3
- Build Modules:    -

### What went wrong?

Creating a page template using the sidebar creates a `.vscode` folder inside the src folder instead of using the root folder.

Setting `defaultTemplate` to `default.page-template` works as expected with generated location, however, it stops working if I manually move `default.page-template` to root `.vscode`.

```
.nuxt
.output
.vscode    < --- should use this folder
src
  .vscode      < --- creates this instead
     default.page-template
  pages
     my-page.vue
package.lock.json
package.json
```

### How to reproduce it?

create a nuxt project that uses a srcDir

create a new page template using the sidebar

notice incorrect .vscode location

**Comment by jaketig** [comment]
Not sure if I'm doing somthing wrong but version 0.2.8 still seems to create a .vscode inside my src folder when creating templates

**Comment by jaketig** [comment]
I also believe this line may need to be changed to use `projectRootDirectory()` instead of `projectSrcDirectory()` 

https://github.com/nuxtrdev/nuxtr-vscode/blob/5594aae33909ad652932e10eb7e9f59ea00c22db/src/utils/files.ts#L13

**Comment by adhamfarrag** [comment]
Hi @jaketig, I failed to reproduce it using 0.2.8. Please can you confirm this is the same approach you're using. Will look into the line you mentioned but I believe it's not what we're looking for. 


![2023-11-16 11 52 50 PM](https://github.com/nuxtrdev/nuxtr-vscode/assets/23562275/2e377171-866c-485b-9e67-c9b5ff9541fb)

**Comment by jaketig** [comment]
When I create the template via the context menu as shown above it works as expected (I didn't notice that was an option lol)

When I create the template via the Sidebar > File Templates > Create New Template it creates a new .vscode inside of src

![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/29202067/326c7721-4df9-4f12-8c9b-40c07609c03d)
![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/29202067/71ec9754-33e2-4b72-846c-4bfe6937b448)

**Comment by adhamfarrag** [comment]
@jaketig  You didn't hurt me at all with ` didn't notice that was an option lol`. :')

Also, sorry I didn't test properly. Will fix it shortly. :)

**Comment by adhamfarrag** [comment]
Actually, this context menu works with selected content in case you just want to copy certian parts of your file. Should make your workflow even easier with creating file templates.

**Comment by adhamfarrag** [comment]
@jaketig 0.2.9 should fix it. Please update. :)

**Comment by jaketig** [comment]
Excellent! Works as expcted now. Thanks for the quick fix!
