### ISSUE TITLE
[Bug]: add new page

### ISSUE THREAD

**Issue by ilovedingle** [nuxtrdev/nuxtr-vscode#88]
### Environment

- Operating System: Linux
- Node Version:     v21.1.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  yarn@1.22.19

### What went wrong?

When i choose to use the script tag as first element, i get a new page file like this:

```
<script lang="ts" setup>

</script>
<template>
  <div>
    
  </div>
</template>


<style lang="scss" scoped>

</style>
```

as you can see there is not a new line after the script tag and there are 2 after the template tag

### How to reproduce it?

create a new page file when you have set the script tag as first element and the template tag as second

**Comment by ilovedingle** [comment]
`<script lang="ts" setup>

</script>
<template>
  <div>
    
  </div>
</template>


<style lang="scss" scoped>

</style>`

this is the code

**Comment by ilovedingle** [comment]
`<script lang="ts" setup>

</script>
<tem>
  <divx>
    
  </divx>
</tem>


<style lang="scss" scoped>

</style>`

this is the code

**Comment by adhamfarrag** [comment]
Hi @ilovedingle, Version 0.2.10 should include fix for this bug. Please, update.

**Comment by ilovedingle** [comment]
What should i have to update, this is my first bug report, so i don't know

**Comment by adhamfarrag** [comment]
@ilovedingle Please update Nuxtr in your VSCode to latest version. :)

**Comment by ilovedingle** [comment]
ok, thanks
