### ISSUE TITLE
[Bug]: .vue is added to filename when .vue is already specified

### ISSUE THREAD

**Issue by DavidDeSloovere** [nuxtrdev/nuxtr-vscode#91]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.8.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  pnpm@8.10.5
- Builder:          -
- User Config:      runtimeConfig, devtools, modules, colorMode, css, i18n, robots, site, sitemap
- Runtime Modules:  @nuxt/devtools@1.0.3, @nuxt/image@1.1.0, @nuxt/ui@2.11.0, @nuxtjs/i18n@8.0.0-rc.5, nuxt-icon@0.6.6, nuxt-simple-robots@3.1.9, nuxt-schema-org@3.2.1, nuxt-simple-sitemap@4.1.6
- Build Modules:    -
------------------------------

### What went wrong?

I know it's my fault. But I'm sure other people have this too.
when creating a new page or component etc.. I have the habit of adding the file extension, ie. `something.vue`. Nuxtr also adds the extension.
So I end up with `something.vue.vue`.

![image](https://github.com/nuxtrdev/nuxtr-vscode/assets/352626/9de873db-bedb-4c63-be10-fdad79c27f07)

### How to reproduce it?

Add new page in the pages folder, enter `something.vue` in the prompt.
You'll have a `something.vue.vue` file.

**Comment by DavidDeSloovere** [comment]
I know it's technically not a bug. Not trying to offend anyone 😀 Rather DX.

**Comment by adhamfarrag** [comment]
Even if it's your fault @DavidDeSloovere :D, always happy to make nuxting better and more fun for you. :sweat_smile:
Should have done it long time ago but somehow I keep forgetting. Will ship it max by next week.

**Comment by corbinu** [comment]
Hello this is happening again in the current version
